<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="mypc" ignored="0" name="Default test" tests="1" failures="1" timestamp="09 Aug 2018 20:29:44 GMT" time="0.087" errors="0">
  <testcase name="test1" time="0.04" classname="com.testngtests.ExceptionTimeOutTestDemo">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.testngtests.ExceptionTimeOutTestDemo.test1() didn&amp;apos;t finish within the time-out 2">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.testngtests.ExceptionTimeOutTestDemo.test1() didn't finish within the time-out 2
at java.io.BufferedWriter.write(BufferedWriter.java:220)
at java.io.Writer.write(Writer.java:157)
at java.io.BufferedWriter.newLine(BufferedWriter.java:243)
at java.io.PrintStream.newLine(PrintStream.java:544)
at java.io.PrintStream.println(PrintStream.java:737)
at com.testngtests.ExceptionTimeOutTestDemo.test1(ExceptionTimeOutTestDemo.java:22)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test -->
